"""empty message

Revision ID: b4777bb727fc
Revises: 
Create Date: 2019-07-13 02:40:26.245089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4777bb727fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('url_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('url'),
    sa.UniqueConstraint('url_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    # ### end Alembic commands ###
